### PR TITLE
Add basic auth support

### PR DESCRIPTION
**Pull request by oligriffiths**
Basic auth support implemented as a user authenticator
Refactored the form authenticator to inherit off the basic auth user authenticator as form authentication is basically the same as basic auth, except an HTML form instead of header values
Added getUser and getPassword methods to DispatcherRequestInterface. It may be worth adding setUser and setPassword methods for consistency, thus the public interface doesn't have to worry about headers.

### CODE REVIEW

**Comment by johanjanssens** [comment]
@oli As explained on the forums work is underway to optimise the authentication implementation which will resolve the issues as mentioned. I also noticed that this PR is not 100% clean and includes the format change, this change is still in development.

**Comment by oli** [comment]
@johanjanssens -> @oligriffiths

**Comment by oligriffiths** [comment]
Great. For reference I cleaned up the PR branch to remove the format change, accidental.

**Comment by johanjanssens** [comment]
Thanks. The fixes I'm working on will supercede this so not going to re-open it.

**Pull request closed without merging**
